apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-1
  labels:
    app: feeds-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeds-1
  template:
    metadata:
      labels:
        app: feeds-1
    spec:
      containers:
      - name: feedsapi
        image: dockertanj/feedsapi
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: POSTGRES_PASSWORD  
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: POSTGRES_HOST  
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: envconfig
              key: POSTGRES_DB         
        