apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-1
  labels:
    app: feeds-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeds-1
  template:
    metadata:
      labels:
        app: feeds-1
    spec:
      containers:
      - name: feedsapi
        image: dockertanj/feedsapi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
